### PR TITLE
chart: Add nodeport and nodeSelector support

### PR DESCRIPTION
**Pull request by morganchristiansson**
Support deploying as NodePort service on specific node

At the time I didn't know k8s_gateway only resolves type: LoadBalancer services and that only type: LoadBalancer get service status.loadbalancer.ip field populated. After deploying k8s_gateway I ended up deploying metallb and will likely go back to using type: LoadBalancer.
Also it turns out type: LoadBalancer was already working by default in k3s with https://github.com/k3s-io/klipper-lb.

But nonetheless this PR correctly adds support for nodePort that I'm currently using :+1:

### CODE REVIEW

**Comment by networkop** [comment]
thanks @morganchristiansson 
so what happens when you configure a nodePort service? does it even work?

**Comment by morganchristiansson** [comment]
This is my values.yaml. The service forwards to normal port 53 on pod.
```
service:
  type: NodePort
  nodePort: 30053

nodeSelector:
  kubernetes.io/hostname: morgan-server
```

In my openwrt dnsmasq.conf I have
```
server=/k8s.lan/192.168.1.190#30053
rebind-domain-ok=/k8s.lan/
```

It was a bit difficult to query dns on non-standard port, many tools don't seem to support specifying port when specifying dns server. But found some that do and it works.

**Review by networkop — CHANGES_REQUESTED** [review]
LGTM. can you bump the chart version please, so that the change gets picked up by CD tools?

**Comment by morganchristiansson** [comment]
I also added support for setting loadBalancerIP requested in #14 and added a README.

Chart version bumped. Thank you! :1st_place_medal:

**Comment by networkop** [comment]
amazing, thanks for your great work @morganchristiansson :tada:

**Comment by morganchristiansson** [comment]
Likewise :+1:

**Pull request merged**
