### PR TITLE
Gateway API v1 (draft)

### PR DESCRIPTION
**Pull request by eduser25**
Gateway api v1 is currently in experimental.
https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.0.0

Seems to be working fine on my setup with minimal changes.

### CODE REVIEW

**Comment by networkop** [comment]
thanks @eduser25 , this is definitely a needed change. note that there's a https://github.com/ori-edge/k8s_gateway/pull/238 in flight which updates CRDs to 0.8.X, so your PR will eventually need a rebase

**Comment by networkop** [comment]
@eduser25 that PR with v0.8.1 GwAPI CRDs is merged, you might need to rebase and update. 
I'll cut a new release once your PR is merged as well

**Comment by larivierec** [comment]
Oh, I was going to create a PR then I saw this.
I'll wait, if you need any help let me know

**Comment by networkop** [comment]
@eduser25  are you planning to finish working on your PR or you'd be ok for https://github.com/ori-edge/k8s_gateway/pull/249 to be merged instead?

**Comment by networkop** [comment]
completed in https://github.com/ori-edge/k8s_gateway/pull/249

**Pull request closed without merging**
