### PR TITLE
chore: update deps

### LINKED ISSUE #83: Bump CoreDNS dep to latest version
Latest version as of now is 1.9.1

https://github.com/coredns/coredns/releases

### LINKED ISSUE #85: Build k8s_gateway with Go 1.18
Currently it is being built with 1.16, it would be great to bump that up to 1.18

### PR DESCRIPTION
**Pull request by onedr0p**
- Update Go to v1.18
- Update caddy to v1.1.1
- Update coredns to v1.9.1
- Update github.com/miekg/dns to v1.1.47
- Update k8s.io/api to v0.23.5
- Update k8s.io/apimachinery to v0.23.5
- Update k8s.io/client-go to v0.23.5
- Update sigs.k8s.io/gateway-api to v0.4.2

Closes #83
Closes #85 

Signed-off-by: Devin Buhl <devin@buhl.casa>

### CODE REVIEW

**Comment by onedr0p** [comment]
That docker workflow seems to be broken for forks.

**Comment by onedr0p** [comment]
@networkop it might be beneficial to enable Renovate on this repo so it can track and open PRs on deps automatically.

https://github.com/apps/renovate

**Comment by networkop** [comment]
great, thanks @onedr0p . Have you used renovate yourself? is it similar to dependabot?

**Comment by onedr0p** [comment]
I use it personally and at work. Renovate is similar but more customizable then dependabot IMO.

**Pull request merged**
