### PR TITLE
Istio Gateway Support

### PR DESCRIPTION
**Pull request by brunocascio**
Hey folks,

This PR includes the support for istio gateway. This is a draft pr because I did not have time to test it in my local machine cluster.

### CODE REVIEW

**Comment by anthr76** [comment]
Should the gateway terminolgy be revised to support Kubernetes Sigs Gateway? I'm pretty sure we would need to extract HTTPRoutes (VS equivlant as I understand) from there, but it would be great for k8s_gateway to support that at some point.

**Comment by networkop** [comment]
good point @anthr76 , the "gateway" in the `k8s_gateway` actually comes from the https://gateway-api.sigs.k8s.io/.  The idea was to add it once the API becomes stable. 
so maybe it's worth renaming the current resource to `IstioGateway`? wdyt @brunocascio @anthr76 ?

**Comment by anthr76** [comment]
In agreeance!

**Comment by brunocascio** [comment]
Hey folks! @anthr76 @networkop 

I'm not pretty sure what do you mean with renaming `Gateway` to `IstioGateway`

Actually, `Gateway` is the [istio's resource name](https://istio.io/latest/docs/reference/config/networking/gateway/) 

I'm really new working with the kube api, so maybe I missed something. If you guys can help me with that, I would be appreciate :)

**Comment by anthr76** [comment]
> Hey folks! @anthr76 @networkop
> 
> I'm not pretty sure what do you mean with renaming `Gateway` to `IstioGateway`
> 
> Actually, `Gateway` is the [istio's resource name](https://istio.io/latest/docs/reference/config/networking/gateway/)
> 
> I'm really new working with the kube api, so maybe I missed something. If you guys can help me with that, I would be appreciate :)

Sure, the link in my comment above (https://gateway-api.sigs.k8s.io/) is a new form of ingress much like a lstio gateway/vs, ingress, and traefik ingress route. When the time comes I'm proposing we don't conflict names as names are already confusing to an extent. 

Some better reads perhaps

* https://gateway-api.sigs.k8s.io/implementations/#istio
* https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by networkop** [comment]
hey @brunocascio , is this PR ready for review or did you still want to add something?

**Comment by brunocascio** [comment]
> hey @brunocascio, is this PR ready for review, or did you still want to add something?

Hey, sorry for the delay I was on vacation :)

I have to migrate to use https://gateway-api.sigs.k8s.io/implementations/#istio instead of Istio's gateway resource

I need a little bit of time to investigate how it actually works

**Comment by networkop** [comment]
oh great. I was planning to work gateway API support over the xmas break. but if you wanna do a PR before that, you're welcome.

**Comment by brunocascio** [comment]
> oh great. I was planning to work on gateway API support over the xmas break. but if you wanna do a PR before that, you're welcome.

I don't think I can have this for that date, so go ahead if you plan to implement the gateway :) 

Anyway, any update I have, I'll post here 👍

**Comment by networkop** [comment]
@brunocascio gatewayAPI(HTTPRoute) support has been merged. Did you still want to finish off this PR? I think it could be valuable to others.

**Comment by networkop** [comment]
I'll close this for now, but anyone interested in this functionality, please feel free to re-open and finish it off.

**Pull request closed without merging**
