### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by p3lim**
There were a lot of runtime warnings of `networking.k8s.io/v1beta1` being deprecated in k8s 1.19 (removed in 1.22), so I just updated everything while at it.

The path change for the build stage was to better work with `podman build`/`buildah`.

### CODE REVIEW

**Comment by networkop** [comment]
thanks @p3lim  and I'm fine with this change in general, however I feel like dropping support for v1beta completely is a bit harsh, at least at this stage, while there are plenty of old clusters out there. If you can set up a fallback to v1beta1, e.g. similar to how it's done in Kong, I'll be happy to merge:
https://github.com/Kong/kubernetes-ingress-controller/blob/f5549c425c675520145314bc2806f2b81cb2e8f9/railgun/controllers/configuration/ingress_utils.go#L19

**Comment by networkop** [comment]
otoh, it looks like 1.18 is no longer supported. so maybe it's worth just making the switch.

**Comment by p3lim** [comment]
As long as 1.21 is the least supported version I think it could still be in, but by the time 1.22 is the least supported it needs to be removed: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

I could add backwards compat, but is it worth the time and effort? 1.21 will last another year (end of support April 30th 2022).

If you still want this I _could_ do it, but it'd have to wait as I'm busy all week and well into next week.

**Comment by networkop** [comment]
@adam-ori can you confirm what k8s version you are currently running in production? I'm considering merging this PR since the 1.22 version is released next month and it will not support `networking.k8s.io/v1beta1`.

**Pull request merged**
