### PR TITLE
Fix docker build on PR

### PR DESCRIPTION
**Pull request by morganchristiansson**

### CODE REVIEW

**Comment by morganchristiansson** [comment]
Do we even want/need `${IMG}:${COMMIT}` to be pushed to docker hub? Maybe push here can removed instead of conditionally enabled.

**Comment by networkop** [comment]
My original idea was to have images built for PRs so that it's easier for me to test them. I missed the fact that it relies on local docker credentials. If that's not possible I think docker workflow can be disabled for PRs completely.  wdyt?

**Comment by morganchristiansson** [comment]
I think typically you would build the docker image and run automated tests without pushing the image. Simple CI pipeline.

Apparently however this has caused issue with bitcoin mining in some github projects recently. If the github action runs from your github user... https://old.reddit.com/r/programming/comments/mj572c/github_investigating_cryptomining_campaign/ never seen this happen myself tho.

**Comment by networkop** [comment]
yeah, I reckon I'll drop the docker from running on pull requests then. Nothing is gained from building a docker image and just leaving it on the CI node.

**Comment by networkop** [comment]
fixed in #27

**Pull request closed without merging**
